jobs:
  - job:  macos
    pool:
      vmImage: "macOS-10.13"
    
    strategy:
      matrix:
        Python35:
          python.version: '3.5'
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
 
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: "x64"

    - script: |
        python -m pip install --upgrade pip setuptools
        python -m pip install wheel
      displayName: 'Install dependencies'

    - script: |
        python setup.py bdist_wheel
      displayName: 'Build wheel'

    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'macos'
        targetPath: 'dist'
