jobs:
- job:  win32
  pool:
    vmImage: "windows-2019"

  steps:      
  - script: cinst msys2 --params "\InstallDir=$(System.DefaultWorkingDirectory)/msys64" --no-progress
    displayName: install msys2
  - script: |
      $(System.DefaultWorkingDirectory)\msys64\usr\bin\pacman --noconfirm -Syyuu
      $(System.DefaultWorkingDirectory)\msys64\usr\bin\pacman --noconfirm -Syuu
    displayName: Update MSYS2
  - script: |
      $(System.DefaultWorkingDirectory)\msys64\usr\bin\pacman --noconfirm --needed -S base-devel mingw-w64-i686-toolchain
      $(System.DefaultWorkingDirectory)\msys64\usr\bin\pacman --noconfirm -Scc
      $(System.DefaultWorkingDirectory)\msys64\usr\bin\sed -i "s|#CacheDir.*|CacheDir=/c/Users/%USERNAME%/AppData/Local/Temp|g" /etc/pacman.conf
      del $(System.DefaultWorkingDirectory)\msys64\mingw32\bin\python.exe
    displayName: Install Toolchain
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.5'
      architecture: 'x86'
    displayName: "Set Python version to 3.5"

  - template: build_python.yml

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x86'
    displayName: "Set Python version to 3.6"

  - template: build_python.yml

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x86'
    displayName: "Set Python version to 3.7"

  - template: build_python.yml

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'win32'
      targetPath: 'dist'
