jobs:
  - job:  win64
    pool:
      vmImage: "windows-2019"
    
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: "x64"
      displayName: 'Use python $(python.version)'

    - script: |
        python -m pip install --upgrade pip setuptools
        python -m pip install wheel
      displayName: 'Install dependencies'

    - script: |
        python setup.py bdist_wheel
      displayName: 'Build wheel'

    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'win64_$(python.version)'
        targetPath: 'dist'