jobs:
- job:  win32
  pool:
    vmImage: "windows-2019"

  steps:      
  - script: | 
      cinst msys2 --params "\InstallDir=c:/msys64" --no-progress
      refreshenv
    displayName: install msys2
  - script: |
      c:\tools\msys64\usr\bin\pacman --noconfirm -Syyuu
      c:\tools\msys64\usr\bin\pacman --noconfirm -Syuu
    displayName: Update MSYS2
  - script: |
      c:\tools\msys64\usr\bin\pacman --noconfirm --needed -S base-devel mingw-w64-i686-toolchain
      c:\tools\msys64\usr\bin\pacman --noconfirm -Scc
      c:\tools\msys64\usr\bin\sed -i "s|#CacheDir.*|CacheDir=/c/Users/%USERNAME%/AppData/Local/Temp|g" /etc/pacman.conf
      del c:\tools\msys64\mingw32\bin\python.exe
    displayName: Install Toolchain
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      architecture: 'x86'
    displayName: "Set Python version to 3.8"

  - template: build_python.yml

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x86'
    displayName: "Set Python version to 3.6"

  - template: build_python.yml

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x86'
    displayName: "Set Python version to 3.7"

  - template: build_python.yml

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'win32'
      targetPath: 'dist'
