
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
    vmImage: "windows-2019"

steps:  
- script: |
    choco install msys2 --params "/NoUpdate /InstallDir:$(System.DefaultWorkingDirectory)\msys64"
  displayName: 'Install msys2'

- script: |
      $(System.DefaultWorkingDirectory)\msys64\usr\bin\pacman --noconfirm -Syyuu
      $(System.DefaultWorkingDirectory)\msys64\usr\bin\pacman --noconfirm -Syuu
  displayName: Update MSYS2

- script: |
      $(System.DefaultWorkingDirectory)\msys64\usr\bin\pacman --noconfirm -S mingw-w64-i686-toolchain
  displayName: Install Toolchain

- script: |
    set PATH=$(System.DefaultWorkingDirectory)\msys64\mingw32\bin;%PATH%
    $(System.DefaultWorkingDirectory)\msys64\usr\bin\pacman -S --noconfirm mingw-w64-i686-python
  displayName: Install python
    
- script: |
    set PATH=$(System.DefaultWorkingDirectory)\msys64\mingw32\bin;%PATH%
    where.exe gcc
    where.exe ld
    where.exe python
    python --version
  displayName: Check tools

- script: |
    set PATH=$(System.DefaultWorkingDirectory)\msys64\mingw32\bin;%PATH%
    python -m pip install --upgrade pip setuptools
    python -m pip install wheel
    python setup.py bdist_wheel
  displayName: Build wheel
  
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'win32'
    targetPath: 'dist'