# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

variables:
  CACHE_FOLDER: $(System.DefaultWorkingDirectory)\msys64

trigger:
- master

pr: none

jobs:
  #- template: azure/build_source.yml
  #- template: azure/build_win64.yml
  #- template: azure/build_win32.yml
  #- template: azure/build_manylinux.yml
  - template: azure/build_macos.yml
  
