
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
    vmImage: "windows-2019"

steps:
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml

    choco install msys2 --params "/NoUpdate /InstallDir:$(System.DefaultWorkingDirectory)\msys64"

    dir $(System.DefaultWorkingDirectory)\msys64
  displayName: 'Install msys2'

- script: |
      echo $(System.DefaultWorkingDirectory)
      $(System.DefaultWorkingDirectory)\msys64\usr\bin\pacman --noconfirm -Syyuu
      $(System.DefaultWorkingDirectory)\msys64\usr\bin\pacman --noconfirm -Syuu
  displayName: Update MSYS2

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    architecture: 'x86'
  displayName: "Set Python version to 3.7"

- script: |
    set PATH=$(System.DefaultWorkingDirectory)\msys64\mingw32\bin;%PATH%
    set GOARCH=386
    set CGO_ENABLED=1
    python -m pip install --upgrade pip setuptools
    python -m pip install wheel
    python setup.py bdist_wheel
  displayName: Build wheel